### ISSUE TITLE
cluster-gateway addon status

### ISSUE THREAD

**Issue by wangzd1** [oam-dev/cluster-gateway#42]
How to check the cluster-gateway addon deployed successfully?
I have install the cluster-gateway addon and got some info.

Message :"The status of cluster-gateway add-on is unknow"
Reason: "ManagedClusterAddOnLeaseNotFound"
Status:"Unknow"
Type:"Available"

And I got nothing after exec "kubectl get clustergateway".Is there any way to troubleshoot?

**Comment by yue9944882** [comment]
@wangzd1 hey, the "unknown" status is expected. the cluster-gateway is working if `kubectl get clustergateway` works. we will be fixing the status in a future release soon

**Comment by wangzd1** [comment]
It seems "kubectl get clustergateway" not works,how can i find out what is wrong?

**Comment by yue9944882** [comment]
@wangzd1 can you show us the output of `kubectl get apiservice` and `kubectl -n vela-system get pod` in ur environment?

**Comment by wangzd1** [comment]
kubectl get apiservice:
NAME                                                 SERVICE                                                            AVAILABLE   AGE
v1.                                                  Local                                                              True        14d
v1.admission.cluster.open-cluster-management.io      open-cluster-management-hub/cluster-manager-registration-webhook   True        5d
v1.admission.work.open-cluster-management.io         open-cluster-management-hub/cluster-manager-work-webhook           True        5d
v1.admissionregistration.k8s.io                      Local                                                              True        14d
v1.apiextensions.k8s.io                              Local                                                              True        14d
v1.apps                                              Local                                                              True        14d
v1.authentication.k8s.io                             Local                                                              True        14d
v1.authorization.k8s.io                              Local                                                              True        14d
v1.autoscaling                                       Local                                                              True        14d
v1.batch                                             Local                                                              True        14d
v1.certificates.k8s.io                               Local                                                              True        14d
v1.cluster.open-cluster-management.io                Local                                                              True        5d
v1.coordination.k8s.io                               Local                                                              True        14d
v1.discovery.k8s.io                                  Local                                                              True        14d
v1.events.k8s.io                                     Local                                                              True        14d
v1.networking.k8s.io                                 Local                                                              True        14d
v1.node.k8s.io                                       Local                                                              True        14d
v1.operator.open-cluster-management.io               Local                                                              True        107m
v1.policy                                            Local                                                              True        14d
v1.rbac.authorization.k8s.io                         Local                                                              True        14d
v1.scheduling.k8s.io                                 Local                                                              True        14d
v1.storage.k8s.io                                    Local                                                              True        14d
v1.work.open-cluster-management.io                   Local                                                              True        5d
v1alpha1.addon.open-cluster-management.io            Local                                                              True        5d
v1alpha1.apps.kruise.io                              Local                                                              True        7d3h
v1alpha1.authentication.open-cluster-management.io   Local                                                              True        45h
v1alpha1.cluster.core.oam.dev                        vela-system/cluster-gateway                                        True        4h10m
v1alpha1.cluster.open-cluster-management.io          Local                                                              True        5d
v1alpha1.core.oam.dev                                Local                                                              True        4h11m
v1alpha1.dashboard.tekton.dev                        Local                                                              True        2d7h
v1alpha1.database.hexin.io                           Local                                                              True        4d2h
v1alpha1.extensions.istio.io                         Local                                                              True        7d20h
v1alpha1.install.istio.io                            Local                                                              True        7d22h
v1alpha1.kiali.io                                    Local                                                              True        6d21h
v1alpha1.monitoring.kiali.io                         Local                                                              True        6d21h
v1alpha1.mysql.presslabs.org                         Local                                                              True        7d20h
v1alpha1.proxy.open-cluster-management.io            Local                                                              True        5d4h
v1alpha1.standard.oam.dev                            Local                                                              True        4h11m
v1alpha1.tekton.dev                                  Local                                                              True        2d8h
v1alpha1.telemetry.istio.io                          Local                                                              True        7d21h
v1alpha2.core.oam.dev                                Local                                                              True        4h11m
v1alpha3.networking.istio.io                         Local                                                              True        8d
v1beta1.admissionregistration.k8s.io                 Local                                                              True        14d
v1beta1.apiextensions.k8s.io                         Local                                                              True        14d
v1beta1.apps.kruise.io                               Local                                                              True        7d3h
v1beta1.authentication.k8s.io                        Local                                                              True        14d
v1beta1.authorization.k8s.io                         Local                                                              True        14d
v1beta1.batch                                        Local                                                              True        14d
v1beta1.certificates.k8s.io                          Local                                                              True        14d
v1beta1.cluster.open-cluster-management.io           Local                                                              True        5d
v1beta1.coordination.k8s.io                          Local                                                              True        14d
v1beta1.core.oam.dev                                 Local                                                              True        4h11m
v1beta1.discovery.k8s.io                             Local                                                              True        14d
v1beta1.events.k8s.io                                Local                                                              True        14d
v1beta1.extensions                                   Local                                                              True        14d
v1beta1.flowcontrol.apiserver.k8s.io                 Local                                                              True        14d
v1beta1.networking.istio.io                          Local                                                              True        8d
v1beta1.networking.k8s.io                            Local                                                              True        14d
v1beta1.node.k8s.io                                  Local                                                              True        14d
v1beta1.policy                                       Local                                                              True        14d
v1beta1.rbac.authorization.k8s.io                    Local                                                              True        14d
v1beta1.scheduling.k8s.io                            Local                                                              True        14d
v1beta1.security.istio.io                            Local                                                              True        7d20h
v1beta1.storage.k8s.io                               Local                                                              True        14d
v1beta1.tekton.dev                                   Local                                                              True        2d8h
v2beta1.autoscaling                                  Local                                                              True        14d
v2beta2.autoscaling                                  Local                                                              True        14d

**Comment by wangzd1** [comment]
kubectl get apiservice:
![image](https://user-images.githubusercontent.com/23433396/150117369-a7385ae9-ad43-40a6-8042-6787755bce31.png)

**Comment by wangzd1** [comment]
kubectl -n vela-system get pod：
![image](https://user-images.githubusercontent.com/23433396/150117483-50c2dc4e-18a4-4166-966f-9711ded9fb1d.png)

**Comment by yue9944882** [comment]
@wangzd1 it looks your installation is completely working. i thought you're saying ur setup is failed. by default, the `clustergateway` resources will not be automatically sync'd from `managedcluster` unless you set `--set manualSecretManagement=false` and `--set konnectivityEgress=true` for ur chart. you can follow the instructions at https://open-cluster-management.io/scenarios/pushing-kube-api-requests/

**Comment by wangzd1** [comment]
I have set `manualSecretManagement: false` and `konnectivityEgress: true` in the values.yaml,and there is still not  shown the `clustergateway` resources

**Comment by yue9944882** [comment]
/close

Fixed by https://github.com/oam-dev/cluster-gateway/pull/51
